id: 
name: GitOps.PullRequestIssueManagement
description: Issue management and triage
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Add bug type label for issues coming from VSCode
        triggerOnOwnActions: false
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - bodyContains:
              pattern: "Type: Bug"
          - not:
              or:
                - hasLabel:
                    label: Type:Bug
                - hasLabel:
                    label: Type:Feature
                - hasLabel:
                    label: Type:CustomerSupport
        then:
          - addLabel:
              label: Type:Bug
      - description: Add feature type label for issues coming from VSCode
        triggerOnOwnActions: false
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - bodyContains:
              pattern: "Type: Feature Request"
          - not:
              or:
                - hasLabel:
                    label: Type:Bug
                - hasLabel:
                    label: Type:Feature
                - hasLabel:
                    label: Type:CustomerSupport
        then:
          - addLabel:
              label: Type:Feature
      - description: Check if a Type label is assigned to new issues
        triggerOnOwnActions: false
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - not:
              or:
                - hasLabel:
                    label: Type:Bug
                - hasLabel:
                    label: Type:Feature
                - hasLabel:
                    label: Type:CustomerSupport
          - not:
              or:
                - bodyContains:
                    pattern: "Type: Bug"
                - bodyContains:
                    pattern: "Type: Feature Request"
        then:
          - addReply:
              reply: 'Team, please add a `Type:Bug`/`Type:Feature`/`Type:CustomerSupport` label as applicable.'
          - addLabel:
              label: needs-typeLabel
      - description: Update issue if Type label was assigned and removes needs-typeLabel
        triggerOnOwnActions: false
        if:
          - payloadType: Issues
          - isOpen
          - or:
            - labelAdded:
                label: Type:Bug
            - labelAdded:
                label: Type:Feature
            - labelAdded:
                label: Type:CustomerSupport
        then:
          - if:
              - hasLabel:
                  label: needs-typeLabel
            then:
              - removeLabel:
                  label: needs-typeLabel
    scheduledSearches:
      - description: Close issues that are 'needs-info' and 'Stale', and have not received any activity for 1 week
        frequencies:
          - hourly:
              hour: 1
        filters:
          - isOpen
          - noActivitySince:
              days: 7
          - hasLabel:
              label: needs-info
          - hasLabel:
              label: Stale
          - isNotLabeledWith:
              label: DoNotClose
        actions:
          - addReply:
              reply: "${issueAuthor}, this issue has been closed due to inactivity over 2 weeks. Please feel free to reopen it if you have further information or questions."
          - closeIssue
      - description: Warn the authors on issues that are 'needs-info', and have not received any activity for 1 week
        frequencies:
          - hourly:
              hour: 1
        filters:
          - isOpen
          - noActivitySince:
              days: 7
          - hasLabel:
              label: needs-info
          - isNotLabeledWith:
              label: DoNotClose
          - isNotLabeledWith:
              label: Stale
        actions:
          - addReply:
              reply: "${issueAuthor}, this issue will be closed soon due to inactivity. Please add more information to help us triage this issue."
          - addLabel:
              label: Stale
      - description: Close lower priority non-Feature issues that have not received any activity for 18 months
        frequencies:
          - hourly:
              hour: 1
        filters:
          - isOpen
          - noActivitySince:
              days: 548
          - isNotLabeledWith:
              label: Priority:0
          - isNotLabeledWith:
              label: Priority:1
          - isNotLabeledWith:
              label: Type:Feature
          - isNotLabeledWith:
              label: DoNotClose
        actions:
          - closeIssue
          - addReply:
              reply: "${issueAuthor}, this issue has been closed due to inactivity for 18 months. Please feel free to reopen it if you have further information or questions."
      - description: Add 'needs-typeLabel' to existing issues that do not have a Type label
        frequencies:
          - hourly:
              hour: 1
        filters:
          - isOpen
          - isNotLabeledWith:
              label: Type:Bug
          - isNotLabeledWith:
              label: Type:Feature
          - isNotLabeledWith:
              label: Type:CustomerSupport
          - isNotLabeledWith:
              label: needs-typeLabel
        actions:
          - addLabel:
              label: needs-typeLabel
          - addReply:
              reply: 'Team, please add a `Type:Bug`/`Type:Feature`/`Type:CustomerSupport` label as applicable.'
      - description: TEST - Reply to every testing issue
        frequencies:
          - hourly:
              hour: 1
        filters:
          - isOpen
          - hasLabel:
              label: testing
        actions:
          - addReply:
              reply: "TEST - Scheduled runs work"
      - description: TEST - reply to test issue and close
        frequencies:
          - hourly:
              hour: 1
        filters:
          - isOpen
          - hasLabel:
              label: testing-close
        actions:
          - addReply:
              reply: "TEST - Scheduled runs works and can close issues"
          - closeIssue
onFailure:
onSuccess:
