id: 
name: GitOps.PullRequestIssueManagement
description: Issue management and triage
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Check if a Type label is assigned to new issues
        triggerOnOwnActions: false
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - not:
              or:
                - hasLabel:
                    label: Type:Bug
                - hasLabel:
                    label: Type:Feature
                - hasLabel:
                    label: Type:SupportRequest
        then:
          - addReply:
              reply: "${issueAuthor}, please add a Type:Bug/Type:Feature/Type:SupportRequest label as applicable."
          - addLabel:
              label: Needs-Info
      - description: Update issue if Type label was assigned # removes Needs-Info if someone assigns a type label
        triggerOnOwnActions: false
        if:
          - payloadType: Issues
          - isOpen
          - or:
            - labelAdded:
                label: Type:Bug
            - labelAdded:
                label: Type:Feature
            - labelAdded:
                label: Type:SupportRequest
        then:
          - if:
              - hasLabel:
                  label: Needs-Info
            then:
              - removeLabel:
                  label: Needs-Info
          - if:
              - not:
                  hasLabel:
                    label: Stale
            then:
              - addLabel:
                  label: Stale
    scheduledSearches:
      - description: Close issues that are 'Needs-Info' and 'Stale', and have not received any activity for 1 week
        frequencies:
          - hourly:
              hour: 1
        filters:
          - isOpen
          - noActivitySince:
              days: 7
          - hasLabel:
              label: Needs-Info
          - hasLabel:
              label: Stale
          - isNotLabeledWith:
              label: DoNotClose
        actions:
          - addReply:
              reply: "${issueAuthor}, this issue has been closed due to inactivity over 2 weeks. Please feel free to reopen it if you have further information or questions."
          - closeIssue
      - description: Warn the authors on issues that are 'Needs-Info', and have not received any activity for 1 week
        frequencies:
          - hourly:
              hour: 1
        filters:
          - isOpen
          - noActivitySince:
              days: 7
          - hasLabel:
              label: Needs-Info
          - isNotLabeledWith:
              label: DoNotClose
          - isNotLabeledWith:
              label: Stale
        actions:
          - addReply:
              reply: "${issueAuthor}, this issue will be closed soon due to inactivity. Please add more information to help us triage this issue."
          - addLabel:
              label: Stale
      - description: Close lower priority issues that have not received any activity for 18 months
        frequencies:
          - hourly:
              hour: 1
        filters:
          - isOpen
          - noActivitySince:
              days: 548
          - isNotLabeledWith:
              label: Priority:0
          - isNotLabeledWith:
              label: Priority:1
          - isNotLabeledWith:
              label: DoNotClose
        actions:
          - closeIssue
          - addReply:
              reply: "${issueAuthor}, this issue has been closed due to inactivity for 18 months. Please feel free to reopen it if you have further information or questions."
      - description: TEST - Reply to every testing issue
        frequencies:
          - hourly:
              hour: 1
        filters:
          - isOpen
          - hasLabel:
              label: testing
        actions:
          - addReply:
              reply: "TEST - Scheduled runs work"
      - description: TEST - reply to test issue and close
        frequencies:
          - hourly:
              hour: 1
        filters:
          - isOpen
          - hasLabel:
              label: testing-close
        actions:
          - addReply:
              reply: "TEST - Scheduled runs works and can close issues"
          - closeIssue
onFailure:
onSuccess:
