#!/bin/bash

# Test version of the issue report generator
# This creates a sample report to demonstrate the functionality

OUTPUT_FILE="${OUTPUT_FILE:-sample-issue-report.md}"

echo "📝 Generating sample issue report to demonstrate functionality..."

# Sample data that represents typical VS Marketplace issues
cat > "$OUTPUT_FILE" << 'EOF'
# VS Marketplace Open Issues Report

Generated on: Mon Jan 20 15:30:45 UTC 2025
Repository: microsoft/vsmarketplace
Total Open Issues: 247

## Summary Statistics

### Issue Distribution by Type

| Type | Count | Percentage |
|------|-------|------------|
| Bug | 89 | 36% |
| Feature Request | 102 | 41% |
| Documentation | 12 | 5% |
| Question | 18 | 7% |
| Enhancement | 15 | 6% |
| Other | 8 | 3% |
| Untyped | 3 | 1% |

### Issue Age Distribution

| Duration | Count | Percentage |
|----------|-------|------------|
| Less than 1 week | 23 | 9% |
| 1 week to 1 month | 45 | 18% |
| 1 to 6 months | 89 | 36% |
| 6 months to 1 year | 67 | 27% |
| More than 1 year | 23 | 9% |

### Priority Distribution

| Priority | Count | Percentage |
|----------|-------|------------|
| Priority:0 (Critical) | 5 | 2% |
| Priority:1 (High) | 34 | 14% |
| Priority:2 (Normal) | 156 | 63% |
| No Priority | 52 | 21% |

### Assignment Status

| Status | Count | Percentage |
|--------|-------|------------|
| Assigned | 89 | 36% |
| Unassigned | 158 | 64% |

## Key Insights

### Long-running Issues
- **Issues open for more than 6 months**: 90 issues (36%)
- **Issues open for more than 1 year**: 23 issues (9%)

### Type Analysis
- **Bug vs Feature ratio**: 89 bugs vs 102 feature requests
- **Untyped issues**: 3 issues need type classification

### Priority Analysis
- **High priority issues** (Priority:0 + Priority:1): 39 issues
- **Issues without priority**: 52 issues need prioritization

---

*Report generated by VS Marketplace Issue Analytics*
*For more information, see: https://github.com/microsoft/vsmarketplace*
EOF

echo "✅ Sample report generated: ${OUTPUT_FILE}"
echo ""
echo "📋 This demonstrates the type of report that would be generated:"
echo "  - Issue type distribution (Bug, Feature, Documentation, etc.)"
echo "  - Duration analysis (< 1 week, 1 week-1 month, 1-6 months, 6 months-1 year, > 1 year)"
echo "  - Priority distribution (Priority:0, Priority:1, Priority:2, No Priority)"
echo "  - Assignment status (Assigned vs Unassigned)"
echo "  - Key insights highlighting long-running issues and areas needing attention"
echo ""
echo "🔧 To run against live data, ensure GitHub CLI is authenticated:"
echo "   gh auth login"
echo "   ./scripts/generate-issue-report.sh"